package com.andikhermawan.chat.server;

import com.andikhermawan.chat.commons.Utils;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 *
 * @author dosse
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public MainFrame() {
        initComponents();
    }

    public void addClient(String clientId) {
        JButton button = new JButton();
        button.setText(clientId);
        button.setName(clientId);
        clientPanel.add(button);
        clientPanel.revalidate();
        clientPanel.repaint();
    }
    
    public void removeClient(String clientId) {
        Component clientComponent = null;
        for (Component component : clientPanel.getComponents()) {
            if (component instanceof JButton && clientId.equals(component.getName())) {
                clientComponent = component;
                break;
            }
        }
        
        clientPanel.remove(clientComponent);
        clientPanel.revalidate();
        clientPanel.repaint();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerPanel = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        koneksiPanel = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        port = new javax.swing.JTextField();
        commandPanel = new javax.swing.JPanel();
        shareScreenButton = new javax.swing.JButton();
        showHideLogButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        clientPanel = new javax.swing.JPanel();
        sharePanel = new javax.swing.JPanel();
        logPanel = new javax.swing.JPanel();
        logScrollPane = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        containerPanel.setLayout(new java.awt.BorderLayout());

        sidebarPanel.setPreferredSize(new java.awt.Dimension(200, 419));
        sidebarPanel.setLayout(new java.awt.BorderLayout());

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Port");

        port.setText("1049");

        javax.swing.GroupLayout koneksiPanelLayout = new javax.swing.GroupLayout(koneksiPanel);
        koneksiPanel.setLayout(koneksiPanelLayout);
        koneksiPanelLayout.setHorizontalGroup(
            koneksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(koneksiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(port, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startButton)
                .addContainerGap())
        );
        koneksiPanelLayout.setVerticalGroup(
            koneksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(koneksiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(koneksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebarPanel.add(koneksiPanel, java.awt.BorderLayout.PAGE_START);

        shareScreenButton.setText("Share Screen");

        showHideLogButton.setText("Show / Hide Log");

        javax.swing.GroupLayout commandPanelLayout = new javax.swing.GroupLayout(commandPanel);
        commandPanel.setLayout(commandPanelLayout);
        commandPanelLayout.setHorizontalGroup(
            commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commandPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shareScreenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showHideLogButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        commandPanelLayout.setVerticalGroup(
            commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, commandPanelLayout.createSequentialGroup()
                .addContainerGap(329, Short.MAX_VALUE)
                .addComponent(shareScreenButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showHideLogButton)
                .addContainerGap())
        );

        sidebarPanel.add(commandPanel, java.awt.BorderLayout.CENTER);

        containerPanel.add(sidebarPanel, java.awt.BorderLayout.LINE_START);

        contentPanel.setLayout(new java.awt.BorderLayout());

        mainPanel.setLayout(new java.awt.BorderLayout());

        clientPanel.setPreferredSize(new java.awt.Dimension(10, 80));
        mainPanel.add(clientPanel, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout sharePanelLayout = new javax.swing.GroupLayout(sharePanel);
        sharePanel.setLayout(sharePanelLayout);
        sharePanelLayout.setHorizontalGroup(
            sharePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sharePanelLayout.setVerticalGroup(
            sharePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );

        mainPanel.add(sharePanel, java.awt.BorderLayout.CENTER);

        logPanel.setMinimumSize(new java.awt.Dimension(100, 140));
        logPanel.setPreferredSize(new java.awt.Dimension(456, 160));
        logPanel.setLayout(new java.awt.BorderLayout());

        logScrollPane.setPreferredSize(new java.awt.Dimension(100, 82));

        log.setEditable(false);
        log.setColumns(20);
        log.setRows(5);
        log.setBorder(null);
        logScrollPane.setViewportView(log);

        logPanel.add(logScrollPane, java.awt.BorderLayout.CENTER);

        mainPanel.add(logPanel, java.awt.BorderLayout.PAGE_END);

        contentPanel.add(mainPanel, java.awt.BorderLayout.CENTER);

        containerPanel.add(contentPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(containerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if (startButton.getText().equals("Stop")) {
            System.exit(0);
        }

        new Thread() {
            @Override
            public void run() {
                try {
                    Server server = new Server(MainFrame.this, Integer.parseInt(port.getText()));
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(rootPane, ex, getTitle(), JOptionPane.ERROR_MESSAGE);
                    System.exit(0);
                }
            }
        }.start();

        new Thread() { //start logger
            @Override
            public void run() {
                while (true) {
                    Utils.sleep(100);
                    if (!Log.get().equals(log.getText())) {
                        log.setText(Log.get());
                        log.getCaret().setDot(Log.get().length());
                    }
                }
            }
        }.start();

        port.setEnabled(false);
        startButton.setText("Stop");
    }//GEN-LAST:event_startButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel clientPanel;
    private javax.swing.JPanel commandPanel;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel koneksiPanel;
    private javax.swing.JTextArea log;
    private javax.swing.JPanel logPanel;
    private javax.swing.JScrollPane logScrollPane;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField port;
    private javax.swing.JPanel sharePanel;
    private javax.swing.JButton shareScreenButton;
    private javax.swing.JButton showHideLogButton;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
